[Feature] edit product and clear code
thanhit23/learning-ReactJs-Redux pull request #2
Opened 2022-08-21 16:38 UTC by thanhit23

2022-08-22 02:09 UTC, tannguyenit requested changes
Update lại code

2022-08-22 02:09 UTC, tannguyenit commented on src/App.js
> +    let { data, filter, keyWord } = this.state;
keyword

2022-08-22 02:09 UTC, tannguyenit commented on src/App.js
> +    onClearForm({
chỗ ni nè, tại sao mỗi lần bấm vô addProduct là clearForm
* ClearForm chỉ chạy khi có id, 
* OnToggleForm luôn luôn chạy 
--> thì cái nên để trong if là clearform

2022-08-22 02:09 UTC, tannguyenit commented on src/App.js
> +const mapStateToProps = ({ isDisForm, editProductReducer }) => {
đặt tên k có thống nhất gì cả
```
isDisForm: Dis là dis gì, viết kiểu này có 1 mình mình hiểu, mà có khi sau 2-3 năm đọc lại chắc cũng k hiểu 
editProductReducer: ??? sao lại có subfix là Reducer trong khi cái trên ko có
```

2022-08-22 02:09 UTC, tannguyenit commented on src/Components/TackForm.js
>    cancelInputValue = () => {
CancelInputValue mà body thì reset data
--> Tên function và nội dung chả liên quan --> chỉ có 2 trường hợp
* Tên function sai
* Body sai 
--> cái nào sai thì sửa lại

2022-08-22 02:09 UTC, tannguyenit commented on src/Components/TackForm.js
> +    if (!isDisForm) return '';
nên return null thay vì ''

2022-08-22 02:09 UTC, tannguyenit commented on src/Components/TackForm.js
> +const mapStateToProps = ({ isDisForm, editProductReducer }) => {
cái ni tương tự ở trên

2022-08-22 02:09 UTC, tannguyenit commented on src/Components/TaskItem.js
> +    const { data, onOpenForm, onEditProduct } = this.props;
detruct 2 thèn `onOpenForm, onEditProduct` làm gì vậy

2022-08-22 02:09 UTC, tannguyenit commented on src/Components/TaskItem.js
> +    const { data: { id }, onUpdateStatus } = this.props;
detruct cái ni làm gì `onUpdateStatus`

2022-08-22 02:09 UTC, tannguyenit commented on src/actions/index.js
> +import {EDIT_PRODUCT_ITEM} from "../consts";
import làm chi ri ????

2022-08-22 02:09 UTC, tannguyenit commented on src/consts/index.js
> +
cuối file chỉ có 1 line trống

2022-08-22 02:09 UTC, tannguyenit commented on src/reducers/handleEditProduct.js
> +
xóa mấy dòng khác, **CHỈ ĐỂ ĐÚNG 1 DÒNG TRỐNG**

2022-08-22 02:09 UTC, tannguyenit commented on src/reducers/tasks.js
>                  status: status === 'false' ? false : true,
satus chỗ ni sao nó lại là string được ?????. Xem lại lúc gửi data đi

2022-08-22 06:15 UTC, tannguyenit requested changes
Check lại comment

2022-08-22 06:15 UTC, tannguyenit commented on src/App.js
> +    if (id) onClearForm(clearData)
chỗ này clearData thì bắn event thôi, vô reducer tự reset thôi, cần chi ở đây truyền

2022-08-22 06:15 UTC, tannguyenit commented on src/App.js
> +          <div className={cl([`col-md-12`], [`col-lg-12`])}>
ko phụ thuộc gì hết thì viết bình thường thôi , k cần xài cl

2022-08-22 06:15 UTC, tannguyenit commented on src/App.js
> +export default YourComponent;
YourComponent ?????

2022-08-22 06:15 UTC, tannguyenit commented on src/Components/TaskList.js
> +export default YourComponent;
lại YourComponent

2022-08-22 06:15 UTC, tannguyenit commented on src/reducers/handleEditProduct.js
> +
chỗ ni vẫn chưa fix

2022-08-22 06:15 UTC, tannguyenit commented on src/reducers/tasks.js
>                  status: status === 'false' ? false : true,
ở đây cũng chưa fix

2022-08-22 15:21 UTC, tannguyenit requested changes
Check my comment

2022-08-22 15:21 UTC, tannguyenit commented on src/App.js
> +          <div className={`col-md-12 col-lg-12`}>
```
<div className="col-md-12 col-lg-12">
```

2022-08-22 15:21 UTC, tannguyenit commented on src/Components/TackForm.js
>      if (!nextProps) return;
k cần biết nhưng nếu kiểm tra thì kiểm tra trên cùng, Tại sao 
Có nghĩa là `const { isEditProduct } = nextProps;` dòng ni đã chạy, rồi mới xuống kiểm tra `if (!nextProps) return;`
Vậy nếu ko có `nextProps` thì vẫn detruct là KHÔNG TỐT ( chứ k phải ko sai ), Tốn effort, kiểu như tốn sức á,

2022-08-22 15:21 UTC, tannguyenit commented on src/Components/TackForm.js
>      if (!nextProps) return;
ví dụ như việc đi cày, 
Dắt con trâu ra đồng 
kiểm tra nếu ko có cái cày thì ở nhà 
??? Vậy tại sao ko kiểm tra ngay ở nhà mà lại đi dắt trâu ra tới đồng mới kiểm tra, --> tốn công sức ( họ gọi là tốn effort )

2022-08-22 15:21 UTC, tannguyenit commented on src/Components/TackForm.js
> +    } else if (isEditProduct === null) {
ủa ủa, cuối cùng cái `isEditProduct` sẽ có bao nhiêu type, null, object, boolean hay như nào ???

2022-08-22 15:21 UTC, tannguyenit commented on src/Components/TackForm.js
> +    this.resetOriginalData();
thường thường sẽ là resetToXXX

2022-08-22 15:21 UTC, tannguyenit commented on src/Components/TackForm.js
> +    const { isDisForm, onCloseForm } = this.props
cách lý giải này như cái trên, có nghĩa là check cái isDisForm trước khi detruct mấy thứ khác

2022-08-22 15:21 UTC, tannguyenit commented on src/reducers/tasks.js
> +                status: Boolean(status),
tại sao chỗ ni cần phải parse cái status value nhỉ, đơn giản là lúc truyền nó thì set về boolean là được , nên xử lý lúc gọi chứ đừng xử lý nơi nhận

2022-08-22 15:21 UTC, tannguyenit commented on src/reducers/tasks.js
> +            const { id: idUpdate, name: nameUpdate, status: statusUpdate} = state[index]
tại sao phải alias cái name làm gì vậy

2022-08-23 03:03 UTC, tannguyenit requested changes
Check my comment

2022-08-23 03:03 UTC, tannguyenit commented on src/App.js
>              <Control searchKeywords={ this.searchKeywords } sortNameOnChange={ this.sortNameOnChange }/>
Update style component

2022-08-23 03:03 UTC, tannguyenit commented on src/Components/TackForm.js
> +    } else if (isEditProduct === null) {
chỗ này chưa trả lời

2022-08-23 03:03 UTC, tannguyenit commented on src/reducers/tasks.js
> +            const { id: idUpdate, name: nameUpdate, status: statusUpdate} = state[index]
Chưa trả lời chỗ này

2022-08-23 03:37 UTC, thanhit23 commented on src/Components/TackForm.js
> +    } else if (isEditProduct === null) {
isEditProduct nó là Object

2022-08-23 03:37 UTC, thanhit23 commented on src/reducers/tasks.js
> +            const { id: idUpdate, name: nameUpdate, status: statusUpdate} = state[index]
nó trùng với thèn ở trên nên phải alias

2022-08-23 03:48 UTC, merged